#!/usr/bin/env bash
set -euo pipefail

# Resolve repo root and make your package importable once, up front (https://saturncloud.io/blog/how-to-get-the-directory-where-a-bash-script-is-located/)
ROOT="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
export PYTHONPATH="$ROOT/src${PYTHONPATH:+:$PYTHONPATH}"

# Environment variables
export LOG_FILE="${LOG_FILE:-$ROOT/logs/phase1.log}"
export LOG_LEVEL="${LOG_LEVEL:-2}"
# GITHUB_TOKEN and GEN_AI_STUDIO_API_KEY should be provided by the environment (AWS Secrets Manager in Fargate)

cmd="${1:-}"

if [[ -z "$cmd" ]]; then
    echo "Usage: ./run install|test|<model_url>"
    exit 1

elif [[ "$cmd" == "install" ]]; then
  python3 -m pip install --user -r "$ROOT/requirements.txt"
  exit 0

elif [[ "$cmd" == "test" ]]; then
  cd "$ROOT"
  python3 "$ROOT/src/ece461/test_summary.py"
  exit 0

else
  python3 -m ece461.main "$cmd"
  echo "$(cat $LOG_FILE)"
  exit 0
fi
