version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ece461-model-registry"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zvcnsi0ylnwj"
s3_prefix = "ece461-model-registry"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
resolve_s3 = false
disable_rollback = true

[default.global.parameters]
region = "us-east-2"
